#!/bin/bash
echo "=== Checking fhir-rest-client installation ==="
ls -la node_modules/fhir-rest-client/ || echo "NOT FOUND"
echo ""
echo "=== fhir-rest-client package.json ==="
cat node_modules/fhir-rest-client/package.json || echo "NOT FOUND"
echo ""
echo "=== fhir-rest-client dist directory ==="
ls -la node_modules/fhir-rest-client/dist/ || echo "NOT FOUND"
echo ""
echo "=== @prismui/react package.json ==="
cat node_modules/@prismui/react/package.json || echo "NOT FOUND"
echo ""
echo "=== @prismui/react dist directory ==="
ls -la node_modules/@prismui/react/dist/ || echo "NOT FOUND"
echo ""
echo "=== Building ==="
npm run build
